version: '3.7'
services:
    consul:
        image: consul:1.7
        ports:
            - "8500:8500"
            - "8300:8300"
            - "53:8600/udp"
        volumes:
            - ./docker/config:/config
            - ./docker/data/consul:/data
        command: agent -ui -server -data-dir=/data -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect=1

    vault:
        image: vault:1.3.2
        ports:
            - "8200:8200"
        environment:
            VAULT_ADDR: 'http://127.0.0.1:8200'
            VAULT_LOCAL_CONFIG: '{"ui": true}'
            VAULT_DEV_ROOT_TOKEN_ID: '00000000-0000-0000-0000-000000000000'
            VAULT_TOKEN: '00000000-0000-0000-0000-000000000000'
        cap_add:
            - IPC_LOCK
        volumes:
            - ./docker/data/vault:/data
        healthcheck:
            retries: 5
        command: server -dev -dev-root-token-id="00000000-0000-0000-0000-000000000000"

    mongodb:
        image: mongo:4.2.3
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
            
    krakend: 
        image: devopsfaith/krakend:1.0
        ports: 
            -  "8080:8080"
        dns: 
            - 192.168.1.2
            - 1.1.1.1
        volumes: 
            - ./docker/krakend:/etc/krakend